version: 0.2

phases:
  #install:
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
       - printenv
       - chmod +x $CODEBUILD_SRC_DIR/script/run.sh
       - $CODEBUILD_SRC_DIR/script/run.sh
  post_build:
    commands:
      - ls
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths